apiVersion: apps/v1
kind: Deployment
metadata:
  name: poccharles-backend
  namespace: poccharles
spec:
  selector: 
    matchLabels:
      app: poccharles-backend
  replicas: 1
  template:
    metadata:
      name: poccharles-backend
      labels:
        app: poccharles-backend
    spec:
      containers:
      - name: backend
        image: ailtonmsj/poccharles-backend:v1
        volumeMounts:
        - name: backend-response
          mountPath: /usr/share/nginx/html
        imagePullPolicy: Always
      volumes:
      - name: backend-response
        configMap:
          name: backend-response
