apiVersion: v1
kind: Service
metadata:
  name: poccharles-backend
  namespace: poccharles
spec:
  selector:
    app: poccharles-backend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
---